In [198]:
#importing necessary libraries 
import pandas as pd
import numpy as np
# import utils

In [199]:
df = pd.read_csv(r"X:\PROGRAMS\NLP PROJECT\datasets\dataset\cleaned_data.csv")

In [200]:
df

,english_gloss,intent,category,department,urgency,severity
0,garbage not collected for 3 days,complaint,sanitation,Sanitation Department,medium,service_delay
1,what is the status of my ration card application?,status_query,certificates,Revenue Department,low,information_query
2,how to apply for new water connection?,information_request,water_supply,Water Supply Department,low,information_query
3,street light is not working,complaint,street_lighting,Electricity Department,medium,service_failure
4,drain is completely blocked,complaint,drainage,Drainage Department,high,public_hazard
...,...,...,...,...,...,...
1255,water supply irregular timing,complaint,water_supply,Water Supply Department,medium,service_failure
1256,drain overflow during rain,complaint,drainage,Drainage Department,high,public_hazard
1257,low voltage issue,complaint,electricity,Electricity Department,medium,service_failure
1258,emergency delay in hospital,complaint,public_health,Public Health Department,high,service_delay
1259,application pending too long,status_query,certificates,Revenue Department,low,service_delay

In [201]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

In [202]:
x = df["english_gloss"].str.lower()
y = df["intent"]

In [203]:
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size = 0.2, random_state = 42)

In [204]:
tfidf_english_gloss = TfidfVectorizer()

In [205]:
x_train = tfidf_english_gloss.fit_transform(x_train)

In [206]:
x_test = tfidf_english_gloss.transform(x_test)

In [207]:
x_train = x_train.toarray()
x_test = x_test.toarray()

In [208]:
#y_transformation 
from sklearn.preprocessing import LabelEncoder

ohe_intent = LabelEncoder()

In [209]:
y_train = ohe_intent.fit_transform(y_train.to_numpy().reshape(-1,1))

c:\Users\ajant\anaconda3\envs\myenv\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [210]:
y_test = ohe_intent.transform(y_test.to_numpy().reshape(-1,1))

c:\Users\ajant\anaconda3\envs\myenv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

In [211]:
# y_train = y_train.argmax(axis=1)
# y_test = y_test.argmax(axis=1)

In [212]:
from sklearn.naive_bayes import GaussianNB

In [213]:
model_intent = GaussianNB()

In [214]:
model_intent.fit(x_train, y_train)

GaussianNB()

In [215]:
y_pred = model_intent.predict(x_test)

In [216]:
from sklearn.metrics import accuracy_score, classification_report

In [217]:
print("Validation Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Validation Accuracy: 0.8849206349206349
              precision    recall  f1-score   support

           0       1.00      0.79      0.88        14
           1       0.99      0.89      0.94       161
           2       1.00      1.00      1.00         2
           3       0.69      1.00      0.82         9
           4       0.69      0.88      0.77        41
           5       0.71      0.62      0.67         8
           6       0.74      1.00      0.85        17

    accuracy                           0.88       252
   macro avg       0.83      0.88      0.85       252
weighted avg       0.91      0.88      0.89       252

In [218]:
import pickle

In [220]:
pickle.dump(model_intent, open(r"X:\PROGRAMS\NLP PROJECT\MODELS\model_intent.pkl", "wb"))
# pickle.dump(tfidf_english_gloss, open(r"X:\PROGRAMS\NLP PROJECT\MODELS\tfidf_english_gloss.pkl", "wb"))
# pickle.dump(ohe_intent, open(r"X:\PROGRAMS\NLP PROJECT\MODELS\ohe_intent.pkl", "wb"))

In [137]:
ohe_intent.classes_

array(['application_help', 'complaint', 'document_help', 'escalation',
       'follow_up', 'information_request', 'status_query'], dtype=object)

from sklearn.naive_bayes import GaussianNB
model_intent = GaussianNB()
model_intent.fit(x_train, y_train)
y_pred = model_intent.predict(x_test)

print("Validation Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

In [186]:
df

,english_gloss,intent,category,department,urgency,severity
0,garbage not collected for 3 days,complaint,sanitation,Sanitation Department,medium,service_delay
1,what is the status of my ration card application?,status_query,certificates,Revenue Department,low,information_query
2,how to apply for new water connection?,information_request,water_supply,Water Supply Department,low,information_query
3,street light is not working,complaint,street_lighting,Electricity Department,medium,service_failure
4,drain is completely blocked,complaint,drainage,Drainage Department,high,public_hazard
...,...,...,...,...,...,...
1255,water supply irregular timing,complaint,water_supply,Water Supply Department,medium,service_failure
1256,drain overflow during rain,complaint,drainage,Drainage Department,high,public_hazard
1257,low voltage issue,complaint,electricity,Electricity Department,medium,service_failure
1258,emergency delay in hospital,complaint,public_health,Public Health Department,high,service_delay
1259,application pending too long,status_query,certificates,Revenue Department,low,service_delay

In [191]:
y_category = df["severity"]

In [192]:
cat_xtrain, cat_xtest, severity_ytrain, severity_ytest = train_test_split( x, y_category, test_size = 0.2, random_state = 42)

In [193]:
severity_LE = LabelEncoder()

In [194]:
severity_ytrain = severity_LE.fit_transform(severity_ytrain)
severity_ytest = severity_LE.transform(severity_ytest)

In [195]:
from sklearn.naive_bayes import GaussianNB
model_severity = GaussianNB()
model_severity.fit(x_train, severity_ytrain)
y_pred = model_severity.predict(x_test)

print("Validation Accuracy:", accuracy_score(severity_ytest, y_pred))
print(classification_report(severity_ytest, y_pred))

Validation Accuracy: 0.8452380952380952
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00         3
           5       0.75      1.00      0.86        21
           6       0.91      0.90      0.91        70
           7       0.93      0.82      0.87        84
           8       0.89      0.87      0.88        68
           9       0.09      0.50      0.15         2
          10       0.00      0.00      0.00         2

    accuracy                           0.85       252
   macro avg       0.36      0.41      0.37       252
weighted avg       0.87      0.85      0.85       252

c:\Users\ajant\anaconda3\envs\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\ajant\anaconda3\envs\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\ajant\anaconda3\envs\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\ajant\anaconda3\envs\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\ajant\anaconda3\envs\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\ajant\anaconda3\envs\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [196]:
severity_LE.classes_

array(['authority_issue', 'health_hazard', 'health_issue', 'health_risk',
       'information', 'information_query', 'public_hazard',
       'service_delay', 'service_failure', 'service_issue',
       'service_request', 'status'], dtype=object)

In [197]:
pickle.dump(model_severity, open(r"X:\PROGRAMS\NLP PROJECT\MODELS\model_severity.pkl", "wb"))
pickle.dump(severity_LE, open(r"X:\PROGRAMS\NLP PROJECT\MODELS\severity_LE.pkl", "wb"))